# Generated by Django 3.1.2 on 2020-10-11 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chitchat', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatmessage',
            old_name='user',
            new_name='sender',
        ),
    ]
