# Generated by Django 3.1.2 on 2020-10-14 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('botGame', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botmodel',
            name='bot_room_name',
        ),
        migrations.AddField(
            model_name='botmodel',
            name='player_username',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
