# Generated by Django 3.1.2 on 2020-10-25 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Public'), (1, 'Friend')], default=0, verbose_name='Type'),
        ),
    ]
