# Generated by Django 3.1.2 on 2020-10-08 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='unique_game_id',
            field=models.CharField(default='xx', max_length=10, verbose_name='Unique ID'),
        ),
    ]
