# Generated by Django 3.1.2 on 2020-10-09 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_auto_20201008_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gameroom',
            name='unique_game_id',
            field=models.CharField(max_length=10, unique=True, verbose_name='Unique ID'),
        ),
    ]
