# Generated by Django 3.1.2 on 2020-10-09 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20201009_0746'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Is Online'),
        ),
    ]
