# Generated by Django 3.1.2 on 2020-10-30 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_gamehistory_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='seed',
            field=models.FloatField(default=0.0, verbose_name='Seed'),
        ),
    ]
