# Generated by Django 3.1.2 on 2020-10-10 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_player_is_online'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('R', 'Red'), ('B', 'Blue'), ('G', 'Green'), ('Y', 'Yellow'), ('W', 'Wild'), ('WF', 'Wild Four')], max_length=2, verbose_name='Color')),
                ('number', models.PositiveSmallIntegerField(choices=[(0, 'Zero'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven'), (8, 'Eight'), (9, 'Nine'), (10, 'Skip'), (11, 'Draw Two'), (12, 'Reverse')], verbose_name='Number')),
            ],
        ),
        migrations.CreateModel(
            name='Deck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gameroom', verbose_name='Game Room')),
            ],
        ),
        migrations.CreateModel(
            name='Hand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gameroom', verbose_name='Game Room')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player', verbose_name='Player')),
            ],
        ),
        migrations.CreateModel(
            name='HandCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.card', verbose_name='Card')),
                ('hand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.hand', verbose_name='Hand')),
            ],
        ),
        migrations.CreateModel(
            name='DeckCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.card', verbose_name='Card')),
                ('deck', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.deck', verbose_name='Deck')),
            ],
        ),
    ]
