# Generated by Django 3.1.2 on 2020-10-10 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0005_card_deck_deckcard_hand_handcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hand',
            name='game_room',
        ),
    ]
