# Generated by Django 3.1.2 on 2020-10-10 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0006_remove_hand_game_room'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRoomDeckCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.card', verbose_name='Card')),
                ('game_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gameroom', verbose_name='Game Room')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerHandCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.card', verbose_name='Card')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.player', verbose_name='Player')),
            ],
        ),
        migrations.RemoveField(
            model_name='deckcard',
            name='card',
        ),
        migrations.RemoveField(
            model_name='deckcard',
            name='deck',
        ),
        migrations.RemoveField(
            model_name='hand',
            name='player',
        ),
        migrations.RemoveField(
            model_name='handcard',
            name='card',
        ),
        migrations.RemoveField(
            model_name='handcard',
            name='hand',
        ),
        migrations.DeleteModel(
            name='Deck',
        ),
        migrations.DeleteModel(
            name='DeckCard',
        ),
        migrations.DeleteModel(
            name='Hand',
        ),
        migrations.DeleteModel(
            name='HandCard',
        ),
    ]
