# Generated by Django 3.1.2 on 2020-10-11 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0007_auto_20201010_1905'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='is_game_running',
            field=models.BooleanField(default=False, verbose_name='Is Game Running'),
        ),
    ]
