# Generated by Django 3.1.2 on 2020-10-11 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0010_auto_20201011_1811'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameroom',
            name='online_player_count',
        ),
    ]
