# Generated by Django 3.1.2 on 2020-10-14 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_remove_gameroom_online_player_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gameroomdeckcard',
            name='card',
        ),
        migrations.RemoveField(
            model_name='gameroomdeckcard',
            name='game_room',
        ),
        migrations.RemoveField(
            model_name='playerhandcard',
            name='card',
        ),
        migrations.RemoveField(
            model_name='playerhandcard',
            name='player',
        ),
        migrations.DeleteModel(
            name='Card',
        ),
        migrations.DeleteModel(
            name='GameRoomDeckCard',
        ),
        migrations.DeleteModel(
            name='PlayerHandCard',
        ),
    ]
