# Generated by Django 3.1.2 on 2020-10-14 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0011_remove_gameroom_online_player_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='number',
            field=models.PositiveSmallIntegerField(choices=[(13, 'None'), (0, 'Zero'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven'), (8, 'Eight'), (9, 'Nine'), (10, 'Skip'), (12, 'Draw Two'), (11, 'Reverse')], verbose_name='Number'),
        ),
    ]
