# Generated by Django 3.1.2 on 2020-10-16 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0012_auto_20201014_1947'),
        ('game', '0012_auto_20201014_0814'),
    ]

    operations = [
    ]
