# Generated by Django 3.1.2 on 2020-10-16 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0013_merge_20201016_0452'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('R', 'Red'), ('B', 'Blue'), ('G', 'Green'), ('Y', 'Yellow'), ('W', 'Wild'), ('WF', 'Wild Four')], max_length=2, verbose_name='Category')),
                ('number', models.PositiveSmallIntegerField(choices=[(13, 'None'), (0, 'Zero'), (1, 'One'), (2, 'Two'), (3, 'Three'), (4, 'Four'), (5, 'Five'), (6, 'Six'), (7, 'Seven'), (8, 'Eight'), (9, 'Nine'), (10, 'Skip'), (12, 'Draw Two'), (11, 'Reverse')], verbose_name='Number')),
            ],
        ),
    ]
