# Generated by Django 3.1.2 on 2020-10-25 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='winning_streak',
            field=models.IntegerField(default=0, verbose_name='Winning Streak'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='won_games_count',
            field=models.IntegerField(default=0, verbose_name='Count of Games Won'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='won_rounds_count',
            field=models.IntegerField(default=0, verbose_name='Count of Rounds Won'),
        ),
    ]
