# Generated by Django 3.1.2 on 2020-10-25 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0002_auto_20201025_1247'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='total_games_count',
            field=models.IntegerField(default=0, verbose_name='Count of Games Played'),
        ),
    ]
