# Generated by Django 3.1.2 on 2020-10-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0004_auto_20201025_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_online',
            field=models.BooleanField(default=False, verbose_name='Is Online'),
        ),
    ]
