# Generated by Django 3.1.2 on 2020-10-27 07:35

from django.db import migrations, models
import imagekit.models.fields
import user_profile.models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_userprofile_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=imagekit.models.fields.ProcessedImageField(blank=True, default='default_male.jpg', null=True, upload_to=user_profile.models.user_directory_path),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_rating',
            field=models.IntegerField(default=0, verbose_name='Current Rating'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='maximum_rating',
            field=models.IntegerField(default=0, verbose_name='Maximum Rating'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='current_league',
            field=models.CharField(choices=[('Noobie', 'Noobie'), ('Expert', 'Expert'), ('Champion', 'Champion'), ('Universe Boss', 'Universe Boss')], default='Noobie', max_length=255, verbose_name='Current League'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='maximum_league',
            field=models.CharField(choices=[('Noobie', 'Noobie'), ('Expert', 'Expert'), ('Champion', 'Champion'), ('Universe Boss', 'Universe Boss')], default='Noobie', max_length=255, verbose_name='Maximum League'),
        ),
    ]
