# Generated by Django 3.1.2 on 2020-10-30 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0007_auto_20201030_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_league_changed',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Is League Changed'),
        ),
    ]
