# Generated by Django 3.1.2 on 2020-10-30 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0008_auto_20201030_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_league_changed',
            field=models.PositiveSmallIntegerField(choices=[(0, 'League Stable'), (1, 'League Upgraded'), (2, 'League Degraded')], default=0, verbose_name='Is League Changed'),
        ),
    ]
