# Generated by Django 3.1.2 on 2020-10-31 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0011_remove_userprofile_maximum_league'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='total_games_count',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='won_games_count',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='won_rounds_count',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_custom_games_count',
            field=models.IntegerField(default=0, verbose_name='# of Custom Games Played'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='total_public_games_count',
            field=models.IntegerField(default=0, verbose_name='# of Public Games Played'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='won_custom_games_count',
            field=models.IntegerField(default=0, verbose_name='# of Custom Games Won'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='won_public_games_count',
            field=models.IntegerField(default=0, verbose_name='# of Public Games Won'),
        ),
    ]
