# Generated by Django 3.1.2 on 2020-11-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0012_auto_20201031_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='xp',
            field=models.IntegerField(default=10, verbose_name='XP'),
        ),
    ]
